### ISSUE TITLE
jboss-extras

### ISSUE THREAD

**Issue by fcorneli** [CentEAP/eap-build#173]
Within my company, we have created a JBoss Modules package (ZIP) that contains some extra modules that we use per default on our JBoss instances. We've been using this for a few years now.
Rationale: While the vanilla wants to stress on how small WildFly/EAP is in megabytes because cloud, serverless, whatever other bullshit-look-how-cool-I-am nonsense, the real world turns otherwise: we want an application server that comes with common sense dependencies already bundled with it. Hence we want a fat application server so our apps can remain as lightweight as possible.

This package already bundles the following:
Module com.mysql
    MySQL version: 5.1.49

Module com.mysql:8.0
    MySQL version: 8.0.28

Module org.apache.commons.compress
    Commons Compress version: 1.21

Module org.apache.commons.validator
    Commons Validator version: 1.7

Module org.apache.commons.digester
    Commons Digester version: 2.1

Module org.apache.commons.fileupload
    Commons FileUpload version: 1.4

Module com.google.gson
    GSON version: 2.8.9

Module org.apache.commons.net
    Commons Net version: 3.8.0

Module org.springframework.spring
    Spring version: 5.2.19.RELEASE

Module org.mariadb
    MariaDB Client version: 3.0.3

If there is some interest in creating such a common JBoss EAP modules package, please make some noise here...
The idea would be to add a Maven project as part of `eap-build` that delivers this ZIP package. @hasalex What do you think?

**Comment by hasalex** [comment]
Done : https://github.com/CentEAP/eap-extras
