### ISSUE TITLE
Move eap-build to an organization

### ISSUE THREAD

**Issue by hasalex** [CentEAP/eap-build#176]
More and more people are getting active on the eap-build project, and I'm getting less and less active.
It would be safe for the project to move to an independant GH organization.

And we could add additional projects related to EAP:
* an example application in order to test the build,
* put docker builds outside of the main project,
* add some #173.

What do you think @fcorneli , @cher1705 and the others ?

**Comment by fcorneli** [comment]
@hasalex Allowing to have multiple projects under one umbrella GitHub organization would indeed make sense to avoid turning `eap-build` into a too hairy beast.
You gave me write access a few years ago, but I always have hesitated to merge myself without the approval of "the big boss" per PR. :) Here an organization where multiple people can give feedback and approve will certainly help and also allows participants to deviate focus from this project more easily if they feel like.

So yes, why not.

**Comment by hasalex** [comment]
OK, I don't see any other comment.
So we'll move the repository to an organization.

Any idea for the name ?
I already have 2 org that I don't use : BuildThemAll and CentEAP.

WDYT @fcorneli, @cher1705 and the others ?

**Comment by fcorneli** [comment]
:) Reminds me of this one:
```
dig centas.org

; <<>> DiG 9.10.6 <<>> centas.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2057
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;centas.org.			IN	A

;; AUTHORITY SECTION:
centas.org.		300	IN	SOA	ns1.redhat.com. noc.redhat.com. 2022022800 3600 1800 604800 86400
```

**Comment by hasalex** [comment]
:)) and CentAS exists on GH since 2011, without any activity.

**Comment by fcorneli** [comment]
Back then I suggested once on some forum that what we need is a CentAS... :)
