### ISSUE TITLE
timeline for supporting for JBOSS 8

### ISSUE THREAD

**Issue by karansachdeva24** [CentEAP/eap-build#193]
Any rough targets for JBOSS 8 support

https://developers.redhat.com/articles/2024/02/05/whats-new-jboss-enterprise-application-platform-8?sc_cid=7015Y000003sfSQQAY

**Comment by fcorneli** [comment]
EAP 8 compiles with the existing build-eap7.sh.
You just has to add the version (as usual), and comment out:
```
maven_build servlet-feature-pack
```

**Comment by dinhtran-dev** [comment]
Hi @fcorneli , I'm trying to build JBOSS 8.0.0 and got stuck here.

`
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WildFly: EE Feature Pack Parent 8.0.0.GA-redhat-00011:
[INFO] 
[INFO] WildFly: EE Feature Pack Parent .................... SUCCESS [  2.976 s]
[INFO] WildFly: EE Feature Pack Shared Galleon Content .... SUCCESS [  3.268 s]
[INFO] WildFly: EE Feature Pack Product Configuration ..... SUCCESS [  0.563 s]
[INFO] WildFly: EE Feature Pack Local Galleon Content ..... SUCCESS [  0.333 s]
[INFO] WildFly: EE Full Galleon Pack ...................... SUCCESS [ 20.277 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.680 s
[INFO] Finished at: 2024-02-21T09:02:30Z
[INFO] ------------------------------------------------------------------------
...done with Maven build for ee-feature-pack
=== Maven build for dist ===
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< org.jboss.eap:wildfly-ee-dist >--------------------
[INFO] Building WildFly: EE Full Distribution 8.0.0.GA-redhat-00011
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.jboss.eap:wildfly-testsuite-shared:jar:8.0.0.GA-redhat-00011 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.556 s
[INFO] Finished at: 2024-02-21T09:02:32Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wildfly-ee-dist: Could not resolve dependencies for project org.jboss.eap:wildfly-ee-dist:jar:8.0.0.GA-redhat-00011: Failure to find org.jboss.eap:wildfly-testsuite-shared:jar:8.0.0.GA-redhat-00011 in https://maven.repository.redhat.com/ga/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-eap has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

I checked the missing dependency in mvnrepository, but the latest version is [7.4.13.GA-redhat-00002].

<img width="1165" alt="image" src="https://github.com/CentEAP/eap-build/assets/55644889/a7d66144-e78a-49bd-9c02-83f6dfc29c1e">

Is there anything else I need to do to build JBOSS 8?

**Comment by fcorneli** [comment]
Exclude this, like we always do.
See example patch:
https://github.com/CentEAP/eap-build/commit/6285672ace585c5b9b88901dc6d1916f4e20b6e6

**Comment by dinhtran-dev** [comment]
Hi @fcorneli , Thanks for your quickly reply, It works.

**Comment by fcorneli** [comment]
See also:
https://github.com/CentEAP/eap-build/pull/195

**Comment by fcorneli** [comment]
Merged to master.
