### ISSUE TITLE
Problems to build eap 8.0.2

### ISSUE THREAD

**Issue by henschi** [CentEAP/eap-build#198]
Has anyone tried to build eap 8.0.2?

When I make changes in jboss-eap-8.properties as in version 8.0.0, I get the error below.
Very strange version numbers.
The source package jboss-eap-8.0.2-src.zip shows a version 8.0.3.GA-redhat-00001 !
Artifact 21.0.8.Final-redhat-00001 is missing, but 21.0.9 exists.

Any ideas?

Downloaded from jboss-eap: https://maven.repository.redhat.com/ga/org/jboss/eap/wildfly-client-all/8.0.3.GA-redhat-00001/wildfly-client-all-8.0.3.GA-redhat-00001.jar (20 MB at 408 kB/s)
Downloading from central: https://repo1.maven.org/maven2/org/wildfly/core/wildfly-cli/21.0.8.Final-redhat-00001/wildfly-cli-21.0.8.Final-redhat-00001-client.jar
Downloading from central: https://repo1.maven.org/maven2/org/wildfly/core/wildfly-event-logger/21.0.8.Final-redhat-00001/wildfly-event-logger-21.0.8.Final-redhat-00001.jar
Downloading from central: https://repo1.maven.org/maven2/org/wildfly/core/wildfly-version/21.0.8.Final-redhat-00001/wildfly-version-21.0.8.Final-redhat-00001.jar
Downloading from central: https://repo1.maven.org/maven2/org/wildfly/core/wildfly-elytron-integration/21.0.8.Final-redhat-00001/wildfly-elytron-integration-21.0.8.Final-redhat-00001.jar
Downloading from jboss-public-repo: http://repository.jboss.org/nexus/content/groups/public/org/wildfly/core/wildfly-cli/21.0.8.Final-redhat-00001/wildfly-cli-21.0.8.Final-redhat-00001-client.jar
Downloading from jboss-public-repo: http://repository.jboss.org/nexus/content/groups/public/org/wildfly/core/wildfly-event-logger/21.0.8.Final-redhat-00001/wildfly-event-logger-21.0.8.Final-redhat-00001.jar
Downloading from jboss-public-repo: http://repository.jboss.org/nexus/content/groups/public/org/wildfly/core/wildfly-version/21.0.8.Final-redhat-00001/wildfly-version-21.0.8.Final-redhat-00001.jar
Downloading from jboss-public-repo: http://repository.jboss.org/nexus/content/groups/public/org/wildfly/core/wildfly-elytron-integration/21.0.8.Final-redhat-00001/wildfly-elytron-integration-21.0.8.Final-redhat-00001.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for WildFly: EE Feature Pack Parent 8.0.3.GA-redhat-00001:
[INFO] 
[INFO] WildFly: EE Feature Pack Parent .................... SUCCESS [ 13.863 s]
[INFO] WildFly: EE Feature Pack Shared Galleon Content .... FAILURE [04:15 min]
[INFO] WildFly: EE Feature Pack Product Configuration ..... SKIPPED
[INFO] WildFly: EE Feature Pack Local Galleon Content ..... SKIPPED
[INFO] WildFly: EE Full Galleon Pack ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:35 min
[INFO] Finished at: 2024-06-07T14:46:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wildfly-ee-feature-pack-galleon-shared: Could not resolve dependencies for project org.jboss.eap:wildfly-ee-feature-pack-galleon-shared:pom:8.0.3.GA-redhat-00001: The following artifacts could not be resolved: org.wildfly.core:wildfly-cli:jar:client:21.0.8.Final-redhat-00001, org.wildfly.core:wildfly-elytron-integration:jar:21.0.8.Final-redhat-00001, org.wildfly.core:wildfly-version:jar:21.0.8.Final-redhat-00001, org.wildfly.core:wildfly-event-logger:jar:21.0.8.Final-redhat-00001: Could not find artifact org.wildfly.core:wildfly-cli:jar:client:21.0.8.Final-redhat-00001 in jboss-eap (https://maven.repository.redhat.com/ga/) -> [Help 1]

**Comment by fcorneli** [comment]
Seems indeed like there is something wrong with the released source code. Mixture between 8.0.2 and 8.0.3.

**Comment by hasalex** [comment]
We have the same problem with next version, which is version 8.0.3 on filename but 8.0.5 in pom.xml.

**Comment by hasalex** [comment]
I've started to work on 8.0.3 (see [branch 8.0.3](/CentEAP/eap-build/tree/8.0.3).
I can resolve dependencies with eap and core versions, but now I have following issue:

```
[ERROR] Failed to execute goal org.wildfly.galleon-plugins:wildfly-galleon-maven-plugin:6.3.3.Final:build-feature-pack (feature-pack-build) on project wildfly-core-galleon-pack: Failed to resolve org.jboss:jboss-parent:pom:36: Cannot access jboss-eap (https://maven.repository.redhat.com/ga/) in offline mode and the artifact org.jboss:jboss-parent:pom:36 has not been downloaded from it before. -> [Help 1]
```

... and have no idea how to fix it.

**Comment by fcorneli** [comment]
FYI... 8.0.4 is out.

**Comment by hasalex** [comment]
@fcorneli Thanks
Build is working for version 8.0.4, but result looks ugly...

```
22:32:48,035 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: JBoss EAP 8.0.0.GA (WildFly Core 
21.0.11.Final-redhat-00001) started in 1465ms - Started 281 of 524 services (318 services are lazy, passive 
or on-demand) - Server configuration file in use: standalone.xml
```
I'll need to investigate...

**Comment by hasalex** [comment]
Looks good, just a display issue that can be fixed
See #201
