### ISSUE TITLE
Possibility of removing redhat trademark info to make build prudiction use

### ISSUE THREAD

**Issue by abregar** [CentEAP/eap-build#29]
Reading through some posts on jboss community forum (also the one where hasalex mention this eap-build project of he created - https://community.jboss.org/message/831244#831244) and eula(s?) I am still not fully sure if building eap source makes it production use.

So issue has three sub questions:
- is removing trademark info necessary?
- if yes, how deep (shadowman on webconsole or every redhat mention on every logrecord)
- if yes, is it possible to do?

**Comment by malys** [comment]
To remove trademark, I replace some resources:

```
cp -f ./script/resources/prod_name.png $target/welcome-content/images/

cp -f ./script/resources/product_title.png $target/welcome-content/images/

cp -f ./script/resources/prod_name.png $target/modules/system/layers/base/org/jboss/as/domain-http-error-context/eap/dir/images/

cp -f ./script/resources/product_title.png $target/modules/system/layers/base/org/jboss/as/domain-http-error-context/eap/dir/images/
```
